services:
  backend:
    image: biblioteca-ms-libros
    container_name: biblioteca_ms_libros
    build:
      context: ./biblio-ms-libros-arquetipo
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      # Configuraciones de base de datos
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@vocgyi3vv1p3nvr8_tp?TNS_ADMIN=/app/wallet/
      SPRING_DATASOURCE_USERNAME: BDFS3_BIBLIOTECA
      SPRING_DATASOURCE_PASSWORD: ClaseFullStack3-
    networks:
      - libros_network
    restart: always

  frontend:
    # Configuración básica del contenedor
    image: biblioteca-frontend
    container_name: biblioteca_frontend
    build:
      context: ./biblioteca-frontend
      dockerfile: Dockerfile
    # Configuración de red y dependencias
    ports:
      - "80:80"
    networks:
      - libros_network
    depends_on:
      - backend
    # Configuración de reinicio
    restart: always
    # Variables de entorno
    environment:
      # Configuración de comunicación
      BACKEND_URL: http://backend:8091

networks:
  libros_network:
    driver: bridge
    name: libros_network