version: '1'
services:
  mslibros:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@vocgyi3vv1p3nvr8_tp?TNS_ADMIN=/app/wallet/
      - spring.datasource.username=BDFS3_BIBLIOTECA
      - spring.datasource.password=ClaseFullStack3-
    restart: always