version: '1'
services:
  msusuarios:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@vocgyi3vv1p3nvr8_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=BDFS_SUM2_USUARIOS
      - spring.datasource.password=ClaseFullStack1-
    restart: always